### ISSUE TITLE
주제: 이미 존재하는 관련 사이트 발견

### ISSUE THREAD

**Issue by Doyoung01** [Jiwon-C/CumCum_opensource_project#2]
https://janet.co.kr/

우리가 구현하려고 했던 기능들과 매우 유사한 서비스를 제공하고 있어서 추가 의논이 필요할 것 같습니다.
어차피 공부해본 결과 최초 아이디어를 전부 구현하기에는 무리가 있다고 판단되니 아이디어를 수정하는 게 좋다고 생각합니다.

1. 아예 다른 주제로 전환하거나,
 - 대체 주제(초반 아이디어 회의 때 나왔던 주제)
  1) 과제 분류 사이트 : 확장자, [과목명] 태그로 분류
  2) 공휴일 계산 및 휴가 추천 사이트

2. 현재 사이트의 대상 등을 수정
 - 대상 : 대학생/취준생 등 -> 충북대학교 혹은 전자정보대학 소속 학생(대학 재학생은 정보처리기사 같은 경우 응시 자격 때문에 4학년 1학기 이후부터 응시할 수 있음, 이때 재학 학년과 학기를 선택하도록 함(ex. 3학년 1학기, 4학년 2학기))
  └ '학과별'로 나눠지는 것에는 여전히 차별성이 있다고 생각해, 사용자들의 범위를 위와 같이 구체화하면 좋겠다고 생각했습니다.

**Comment by meemoon** [comment]
현재 주제에서 사용자 범위를 충북대 전자정보대학 소속학생으로 고정시키는 게 좋겠습니다.  전정대 학생이 하나의 자격증에 대해 검색하는 기능보다, 이 학과에 주요한 자격증들이 뭐가 있는지 알려주는 것에 의미를 두고 학년, 학기별 선택지를 사용자가 선택하고 그 학년, 학기에 맞는 자격요견의 자격증 정보를 제공하는 것으로 구현하는 것은 어떨까요?

**Comment by Doyoung01** [comment]
저는 좋습니다. 그럼 각 학과와 관련된 자격증을 세부적으로 다시 조사할 필요가 있을 것 같은데, 인터넷 조사를 기본으로 하되 타과 학생에게도 가능하다면 물어보도록 하는 것으로 할까요?

**Comment by meemoon** [comment]
네 좋습니다.
