### ISSUE TITLE
웹페이지 : 시작 페이지 관련

### ISSUE THREAD

**Issue by meemoon** [Jiwon-C/CumCum_opensource_project#3]
시작 웹페이지에 replit 사이트를 통해 구현해보았습니다.
학과 선택을 drop down list로 하기 보단 목록이 간단하니 각각의 버튼으로 구현했습니다.

![image](https://user-images.githubusercontent.com/74997217/162946934-216f205a-773f-45fa-9c88-329eec5ca241.png)

**Comment by Doyoung01** [comment]
우선 branch로 작업하여 push 부탁드립니다.

학과를 선택했을 때
1. dropdown list로 학년 선택
2. radio button으로 학년 선택
두 가지 중 하나의 방법으로 선택지가 나오는 것도 좋을 것 같습니다.
하지만 2번의 경우 화면이 지저분해질 수도 있을 것 같은데 어떻게 생각하시나요?

(참고로 이전 이슈에서 제가 dropdown list를 사용하려고 했던 것도 위와 같은 이유였습니다.
위 기능에 대한 코드 수정이 어려우시면 제가 추가 작업해봐도 괜찮습니다.)

**Comment by meemoon** [comment]
학년 선택이 추가되서 저도 dropdown list로 하는게 좋을 것 같습니다. 코드 수정 후 올렸습니다!
