### ISSUE TITLE
데이터 : 자격증 리스트

### ISSUE THREAD

**Issue by Doyoung01** [Jiwon-C/CumCum_opensource_project#5]
우선 자격증 리스트(기본 정보 포함)를 엑셀로 작성하는 게 좋을 것 같습니다.
저는 일단 컴퓨터공학과 관련 자격증을 일부 추가해봤습니다.

[자격증리스트.xlsx](https://github.com/Jiwon-C/CumCum_opensource_project/files/8511500/default.xlsx)

**Comment by Doyoung01** [comment]
유효 기간이 없을 경우 따로 명시하지 않는 걸로 합니다.
일단 예시로 컴공-정보처리기사 행의 데이터를 채워놨습니다.
*대학 재학 또는 졸업자 관련 응시 자격 같은 경우 우리는 재학 학기에 따라 보여주는 자격증이 다르니 포함되지 않는 범위는 딱히 화면에 보여주지 않아도 됩니다.(정보처리기사의 경우 유사 자격 소지자, 실무 경력자...)
다만 증명서를 제출해야 하는 경우가 있으니 '4학년 1학기 이상 재학, 증명서 필요' 정도로 적어주면 될 것 같습니다.

[default.xlsx](https://github.com/Jiwon-C/CumCum_opensource_project/files/8713019/default.xlsx)

**Comment by tlsqhrb** [comment]
엑셀에 조건, 유효기간 내용 추가해서 넣었습니다.
[default (2).xlsx](https://github.com/Jiwon-C/CumCum_opensource_project/files/8804363/default.2.xlsx)

**Comment by meemoon** [comment]
컴퓨터공학과 자격증 정보 모두 정리하였습니다.
[default.xlsx](https://github.com/Jiwon-C/CumCum_opensource_project/files/8828920/default.xlsx)
