### ISSUE TITLE
필요성: 설문 조사 시행 관련

### ISSUE THREAD

**Issue by Doyoung01** [Jiwon-C/CumCum_opensource_project#6]
우리 프로젝트의 필요성을 좀 더 타당성 있게 만들기 위해서 설문 조사를 진행해야 할 것 같습니다. (구글 폼 이용)
설문 조사 문항에 들어갔으면 좋겠는 질문에 대해 논의해봅시다.
아래는 제가 생각한 문항입니다. (전정대 학생을 대상으로 개발하기로 아이디어를 수정했으나 설문조사 대상은 충북대학교 학생으로 하는 게 좋을 것 같다고 생각하고 작성한 문항입니다.)

1. 귀하께서 속한 대학은 어디입니까?
2. 귀하께서 속한 학과는 어디입니까?
3. 귀하는 몇 학년입니까? - 휴학 시 마지막으로 재학한 학년 선택 / 1, 2, 3, 4학년
4. 진로가 명확히 정해져있습니까? - 예, 아니오 **-> 섹션 분류**
5. 현재 몇 개의 자격증을 보유하고 계십니까? - 1개, 2개, 3개, 기타
6. 만약 자격증을 보유하고 있다면, 해당 자격증에 대해 어떻게 알게 되셨습니까? (복수 선택) - 선후배의 추천, 교수님의 추천, 인터넷, 학원 등
7. 취득하려는 자격증을 선택할 때, 어려움을 겪은 적이 있습니까? - 예, 아니오
8. 자격증 관련 자료를 찾는데 어려움을 겪은 적이 있습니까? - 예, 아니오
9. 정보처리기사 같은 경우 4학년 1학기 이상 재학한 학생만 응시할 수 있습니다. 이것에 대해 알고 계십니까? - 예, 아니오
10. (우리가 개발 중인 사이트에 대해 설명한 후) 만약 이러한 웹 사이트가 있다면 이용하실 생각이 있습니까?

**Comment by meemoon** [comment]
충북대학교 학생을 대상으로 정보를 모으고 구글폼을 보낼 예정이니 1번 사항은 없어도 될 것 같다고 생각합니다. 

 필요성에 대해 질문하는 것이여서 다른 과 학생들 전부 대상을 하는 것은 좋지만 9번 같은 질문은 전정대 학생들 이외에는 자격증 자체도 잘 모를 학생이 대부분일 것 같아 설문 조사할 대상을 확실하게 전정대로 하거나 9번 질문사항을 없애는 게 나을 것 같습니다.  아니면 응시자격을 알고있는 자격증 수와 그에 대해 알게된 경로를 질문으로 추가하는 것은 어떤가요?

 질문사항에 본인이 취득했거나 취득 예정인 자격증에 대해 질문을 추가하는 것은 어떤가요? 필요성과 더불어 자격증 정보 자료로 좋을 것 같습니다.

**Comment by Doyoung01** [comment]
소속대학은 전자정보대학과 같은 단과대를 말하는 것입니다.

그럼 9번을 다음과 같이 두 가지 질문으로 다시 작성할 수 있을 것 같습니다.
9-1. 자격증에 따라 응시 자격에 제한이 있다는 것을 알고 계십니까?
9-2. 정보처리기사 자격증에 대해 알고 있다면 답변해주십시오. 이 자격증은 대학생일 경우 4학년 1학기 이상 재학한 학생만 응시할 수 있습니다. 이것에 대해 알고 계십니까?

관련 질문 예시를 들어주시면 감사하겠습니다. 지금 생각나는 건 이런 것 밖에 없네요.
- 본인이 취득한 자격증 중 재학 중인 학과에서 필수적이거나 중요하다고 생각하는 것을 적어주십시오.
- 또한, '이것만큼은 따야 한다'고 생각하는 자격증을 적어주십시오.

**Comment by meemoon** [comment]
전정대 학생을 기준으로 작성해주신 질문 9번과 함께, 아래 질문을 추가하는 것은 어떤가요?
9-3. 응시자격을 알게된 경로는 무엇입니까? 1.인터넷 검색  2.주변 사람들을 통해 3.자격증 관련 서적 4. 학원 5. 기타
자격증 (어떤 자격증이 있는지)에 대한 정보를 알게된 경로와 비슷한 예시로 적어봤습니다.

마지막 두 질문은 예시 작성하신대로 작성하는것이 좋은 것 같습니다.
